#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1514966923                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Pump Diary™                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Keep track of your breast milk production & its storage

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : CB Patel
your_link                                 : https://pumpdiaryapp.github.io/main/
your_city                                 : California
email_address                             : pumpdiaryapp@gmail.com
facebook_username                         :
instagram_username                        : pumpdiary
twitter_username                          : pumpdiary
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

    - title                                 : Log Pumping Sessions
      description                           : Keep track of your pumping sessions and add notes during the session
      fontawesome_icon_name                 : magic
      
    - title                                 : Track daily activities in between sessions
      description                           : Add daily activities in between sessions to monitor milk production and impact of the activities e.g. Sleep, Taking Vitamins, Workout etc
      fontawesome_icon_name                 : bed

    - title                                 : Stay on schedule with notifications
      description                           : Set custom reminder and stay on schedule for your next pumping session
      fontawesome_icon_name                 : bell

    - title                                 : Keep track of milk stash
      description                           : Store milk stash record and usage with the easy to enter User Inteface
      fontawesome_icon_name                 : snowflake

    - title                                 : Get Daily and Weekly Stats
      description                           : Get summary of daily and weekly milk production
      fontawesome_icon_name                 : chart-line
  


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
